### PR TITLE
upgrades to get it completely working

### PR DESCRIPTION
**Pull request by pablodav**
* fixes for latest stable ansible
* Upgrade nginx docker version
* updates in template to have better usage
* better README troubleshooting information about nginx
* new vars and examples

### CODE REVIEW

**Comment by marvinpinto** [comment]
Hey @pablodav! This looks reasonable enough :+1: 

If you can try and figure out why Travis is failing, it would be much appreciated. Otherwise I will try and set aside some time in the new year to fix that test + merge this PR.

Thank you again :tada:

**Comment by pablodav** [comment]
Thanks for your reply.

I will check, seems there are many errors to fix, most of them travis deprecated environment that needs to be fixed in travis file so I will take it into my own branch, once fixed will notify.

Probably I will change existing tests into molecule tests as they can be used local or in any CI.

**Comment by marvinpinto** [comment]
@pablodav Thank you again for your time! I've also added you as a collaborator to this repository which should hopefully make things easier.

**Comment by pablodav** [comment]
hello @marvinpinto 

I have fixed the travis tests
migrated to molecule tests
Added docker-py dependency 
Added notes with examples to use docker role.
Also added the docker role in tests as it is a requirements for real systems.
Everything works from scratch now.

**Comment by marvinpinto** [comment]
This is awesome, thank you @pablodav :tada:

**Pull request merged**
